In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import csv
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import StratifiedKFold
%matplotlib inline


# nltk for natural language processing

In [2]:
path =r'./playstorereviewsdata/' # use your path
allFiles = glob.glob(path + "/*.tsv")

# for out_count, file in enumerate(allFiles):
#     with open(file, newline='') as csvfile:
#         spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
#         #import pdb;pdb.set_trace()
#         for counter, row in enumerate(spamreader):
#             import pdb;pdb.set_trace()
#             print(row)
            
#     with open(file+out_count, 'wt') as csvfile:
#             writer = csv.writer(csvfile, delimiter='', quotechar='|')
#             #writer.writerow(["#"] + anarkali_characteristics)
#             #import pdb;pdb.set_trace()
#             for element in lehenga_characteristics:
#                 #import pdb;pdb.set_trace()
#                 writer.writerow([element["name"], element["count"]])

In [3]:
# get full data


frame = pd.DataFrame()
list_ = []

# datacolumns = [
#     "Package Name",
#     "App Version Code",
#     "Reviewer Language",
#     "Device",
#     "Review Submit Date and Time",
#     "Review Submit Millis Since Epoch",
#     "Review Last Update Date and Time",
#     "Review Last Update Millis Since Epoch",
#     "Star Rating",
#     "Review Title",
#     "Review Text",
#     "Developer Reply Date and Time",
#     "Developer Reply Millis Since Epoch",
#     "Developer Reply Text,Review Link"
# ]

for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None, header=0, encoding = "ISO-8859-1", error_bad_lines=False, sep='\t')
    list_.append(df)
    
    
full_data = pd.concat(list_)
full_data.head(5)

,App Version Code,App Version Name,Developer Reply Date and Time,Developer Reply Millis Since Epoch,Developer Reply Text,Device,Package Name,Review Last Update Date and Time,Review Last Update Millis Since Epoch,Review Link,Review Submit Date and Time,Review Submit Millis Since Epoch,Review Text,Review Title,Reviewer Language,Star Rating
0,1.0,NaN,NaN,NaN,NaN,m7,com.flyrobe.android,2015-08-09T07:05:36Z,1439103936468,https://play.google.com/apps/publish?dev_acc=0...,2015-08-09T07:05:36Z,1439103936468,This is a brilliant concept. Please start for ...,Great product!,en,5
1,NaN,NaN,NaN,NaN,NaN,falcon_umtsds,com.flyrobe.android,2015-08-09T10:05:06Z,1439114706593,https://play.google.com/apps/publish?dev_acc=0...,2015-08-09T10:05:06Z,1439114706593,Brilliant concept :),NaN,en,5
2,NaN,NaN,NaN,NaN,NaN,k3g,com.flyrobe.android,2015-08-09T11:51:54Z,1439121114161,https://play.google.com/apps/publish?dev_acc=0...,2015-08-09T11:51:54Z,1439121114160,NaN,NaN,en,5
3,1.0,NaN,NaN,NaN,NaN,htc_m8,com.flyrobe.android,2015-08-09T12:03:11Z,1439121791786,https://play.google.com/apps/publish?dev_acc=0...,2015-08-09T12:03:11Z,1439121791786,Brilliant stuff!! Waiting to see more..,NaN,en,5
4,1.0,NaN,NaN,NaN,NaN,titan_umtsds,com.flyrobe.android,2015-08-09T12:12:04Z,1439122324704,https://play.google.com/apps/publish?dev_acc=0...,2015-08-09T12:12:04Z,1439122324704,NaN,NaN,en,5

In [4]:
# remove the NaN 
full_data["Review Text"] = full_data["Review Text"].fillna('')
full_data["Review Title"] = full_data["Review Title"].fillna('')
full_data["App Version Code"] = full_data["App Version Code"].fillna(0.0)
full_data["App Version Name"] = full_data["App Version Name"].fillna('')
full_data["Developer Reply Date and Time"] = full_data["Developer Reply Date and Time"].fillna('')
full_data["Developer Reply Millis Since Epoch"] = full_data["Developer Reply Millis Since Epoch"].fillna('')
full_data["Developer Reply Text"] = full_data["Developer Reply Text"].fillna('')

# slicing the required columns only
full_data = full_data[["Review Text", "Review Title", "Star Rating"]]

In [5]:
full_data.head(5)

,Review Text,Review Title,Star Rating
0,This is a brilliant concept. Please start for ...,Great product!,5
1,Brilliant concept :),,5
2,,,5
3,Brilliant stuff!! Waiting to see more..,,5
4,,,5

In [6]:
processed_data = full_data.loc[full_data['Review Text'] != '']
sliced_data = processed_data[:1000]
sliced_data.head(5)

,Review Text,Review Title,Star Rating
0,This is a brilliant concept. Please start for ...,Great product!,5
1,Brilliant concept :),,5
3,Brilliant stuff!! Waiting to see more..,,5
5,This idea will be considered as one of the top...,Excellent,5
7,No spending on buying apparels for gf... Why t...,Brilliant ..this is what we needed!!,5

In [7]:
sliced_data['Review Text'].head(5)

0    This is a brilliant concept. Please start for ...
1                                 Brilliant concept :)
3              Brilliant stuff!! Waiting to see more..
5    This idea will be considered as one of the top...
7    No spending on buying apparels for gf... Why t...
Name: Review Text, dtype: object

In [8]:
sliced_data['Review Text'].__len__()

1000

In [ ]:
#Stratified 10-cross fold validation with SVM and Multinomial NB 
labels = np.zeros(1000);
labels[0:500]=0;
labels[500:1000]=1; 
      
kf = StratifiedKFold(n_splits=2)

totalsvm = 0           # Accuracy measure on 2000 files
totalNB = 0
totalMatSvm = np.zeros((2,2));  # Confusion matrix on 2000 files
totalMatNB = np.zeros((2,2));

# tr, te = kf.split(sliced_data['Review Text'], labels)
# td = []
# for i in train_index:
#     td.append(sliced_data['Review Text'][i])
#import pdb;pdb.set_trace()
review_text = sliced_data['Review Text'].tolist()

for train_index, test_index in kf.split(review_text, labels):
    #import pdb;pdb.set_trace()
    X_train = [review_text[i] for i in train_index]
    X_test = [review_text[i] for i in test_index]
    y_train, y_test = labels[train_index], labels[test_index]
    vectorizer = TfidfVectorizer(min_df=1, max_df = 2, sublinear_tf=True, use_idf=True,stop_words='english')
    train_corpus_tf_idf = vectorizer.fit_transform(X_train) 
    test_corpus_tf_idf = vectorizer.transform(X_test)
    #import pdb;pdb.set_trace()
    model1 = LinearSVC()
    model2 = MultinomialNB()    
    model1.fit(train_corpus_tf_idf,y_train)
    model2.fit(train_corpus_tf_idf,y_train)
    result1 = model1.predict(test_corpus_tf_idf)
    result2 = model2.predict(test_corpus_tf_idf)
    
    totalMatSvm = totalMatSvm + confusion_matrix(y_test, result1)
    totalMatNB = totalMatNB + confusion_matrix(y_test, result2)
    totalsvm = totalsvm + sum(y_test==result1)
    totalNB = totalNB + sum(y_test==result2)
    
print(totalMatSvm, totalsvm/1000.0, totalMatNB, totalNB/1000.0)

print(totalMatSvm, totalsvm, totalMatNB, totalNB)

> <ipython-input-10-98aec1465b77>(29)<module>()
-> model1 = LinearSVC()
(Pdb) train_corpus_tf_idf
<500x949 sparse matrix of type '<class 'numpy.float64'>'
	with 1128 stored elements in Compressed Sparse Row format>
(Pdb) c
> <ipython-input-10-98aec1465b77>(28)<module>()
-> import pdb;pdb.set_trace()